# Generated by Django 3.1.2 on 2020-11-04 00:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('AuthorID', models.AutoField(primary_key=True, serialize=False)),
                ('Lastname', models.CharField(max_length=25)),
                ('Firstname', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=40)),
                ('NumberOfPages', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(10)])),
                ('DatePulished', models.DateField()),
                ('Status', models.CharField(choices=[('Available', 'Available'), ('Loaned', 'Loaned'), ('Damaged', 'Damaged')], max_length=9)),
                ('Notes', models.CharField(blank=True, choices=[('Available', 'Available'), ('Loaned', 'Loaned'), ('Damaged', 'Damaged')], max_length=100, null=True)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.author')),
            ],
        ),
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('SuburbID', models.AutoField(primary_key=True, serialize=False)),
                ('SuburbName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('MemberID', models.AutoField(primary_key=True, serialize=False)),
                ('Lastname', models.CharField(max_length=25)),
                ('Firstname', models.CharField(max_length=25)),
                ('DateOfBirth', models.DateField()),
                ('StreetAddress', models.CharField(max_length=25)),
                ('EmailAddress', models.CharField(max_length=30)),
                ('PhoneNumber', models.CharField(max_length=16)),
                ('MembershipType', models.CharField(choices=[('Adult', 'Adult'), ('Child', 'Child')], max_length=5)),
                ('Suburb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.suburb')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loanID', models.AutoField(primary_key=True, serialize=False)),
                ('LoadDate', models.DateField()),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.book')),
                ('Member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.member')),
            ],
        ),
    ]
